# Generated by Django 4.2.5 on 2023-09-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc',
            name='dcCode',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='maingroup',
            name='MainGroupCode',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='PCode',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='salecenter',
            name='saleCenterCode',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='saler',
            name='salerCode',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='SubGroupCode',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='superviseur',
            name='SuperViseurCode',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='topgroup',
            name='TopGroupCode',
            field=models.IntegerField(unique=True),
        ),
    ]
